import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";
import Script from "next/script";
import React from "react";
import LayoutShell from "./layoutShell";
import { designVar } from "@/designVar/desighVar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zest Up | Online Ordering",
  description: "Generated by create next app",
  icons: {
    icon: "/LOGO.png",
    // you can also add a PNG fallback
    shortcut: "/LOGO.png",
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  return (
    <html lang="en">
      {/* Next will fill in <head> for you from `metadata` */}
      <body
        className={cn(
          "min-h-screen flex flex-col max-w-[2500px] w-full mx-auto bg-primaryBg no-scrollbar",
          inter.className,
          designVar.fontFamily
        )}
        suppressHydrationWarning
      >
        {/* your layout shell + Toaster + providers, etc */}
        <LayoutShell>{children}</LayoutShell>
        {/* your external scripts */}
        <Script
          src={process.env.FONT_AWESOME_SCRIPT}
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
